### ISSUE TITLE
Azure pipeline failing -- 0.5.0 was never released

### ISSUE THREAD

**Issue by liamhuber** [conda-forge/pyiron_workflow-feedstock#24]
The last command is

```
+ upload_package --validate --feedstock-name=pyiron_workflow-feedstock /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_64_.yaml
Found git SHA dc36690f03184be43f8696e807ce7bb79cb9c474 for this build!
Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from /home/conda/feedstock_root/.ci_support/linux_64_.yaml
```

Which then results in this loop happening:

```
0%|          | 0.00/87.6k [00:00<?, ?B/s]
93.1kB [00:00, 762kB/s]                    
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
INFO:binstar:Using Anaconda API: https://api.anaconda.org/
Distribution /home/conda/feedstock_root/build_artifacts/noarch/pyiron_workflow-0.5.0-pyhd8ed1ab_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
Distribution /home/conda/feedstock_root/build_artifacts/noarch/pyiron_workflow-0.5.0-pyhd8ed1ab_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
Distribution /home/conda/feedstock_root/build_artifacts/noarch/pyiron_workflow-0.5.0-pyhd8ed1ab_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
Distribution /home/conda/feedstock_root/build_artifacts/noarch/pyiron_workflow-0.5.0-pyhd8ed1ab_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
Distribution /home/conda/feedstock_root/build_artifacts/noarch/pyiron_workflow-0.5.0-pyhd8ed1ab_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
WARNING: Distribution /home/conda/feedstock_root/build_artifacts/noarch/pyiron_workflow-0.5.0-pyhd8ed1ab_0.conda already existed in cf-staging for a while. Deleting and re-uploading.

  0%|          | 0.00/87.6k [00:00<?, ?B/s]
93.1kB [00:00, 1.12MB/s]                   
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
```

Until it finally times out:

```
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
Failed to upload due to copy from staging to production channel failed. Trying again in 153.93679428100586 seconds
Traceback (most recent call last):
  File "/opt/conda/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 248, in upload_package
    retry_upload_or_check(
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 322, in retry_upload_or_check
    raise TimeoutError("Did not manage to upload package.  Failing.")
TimeoutError: Did not manage to upload package.  Failing.
```

Poking around, a similar issue was encountered [last year](https://github.com/conda-forge/pyvista-feedstock/pull/79) and [at least once](https://github.com/conda-forge/conda-forge.github.io/issues/1958) the solution was just to turn the crank again. There is no burning fire for 0.5.0 and 0.6.0 will be ready pretty soon, so I'll close this if that works out, or follow up if I run into the same problem again.

**Comment by liamhuber** [comment]
Just conjecture, but I wonder now if this is also why 0.3.0 never appeared on the release page?

**Comment by jan-janssen** [comment]
Conda had some issues, you can always trigger a new build by just increasing the build number.
